/* generated by ./scripts/generate.ts, do not edit manually */

import React, {ForwardRefRenderFunction, forwardRef} from 'react';
import ArrowDownSVG from '../svg/ArrowDown.svg';
import BaseIcon, {BaseIconProps} from './BaseIcon';

interface IconProps extends Omit<BaseIconProps, 'Icon'> {}

const ArrowDown: ForwardRefRenderFunction<any, IconProps> = (
    props,
    ref,
) => {
  return (
    <BaseIcon {...props} ref={ref} Icon={ArrowDownSVG}/>
  );
};

const ArrowDownIcon = forwardRef(ArrowDown);

export default ArrowDownIcon;
