/* generated by ./scripts/generate.ts, do not edit manually */

import React, {ForwardRefRenderFunction, forwardRef} from 'react';
import ArrowUpSVG from '../svg/ArrowUp.svg';
import BaseIcon, {BaseIconProps} from './BaseIcon';

interface IconProps extends Omit<BaseIconProps, 'Icon'> {}

const ArrowUp: ForwardRefRenderFunction<any, IconProps> = (
    props,
    ref,
) => {
  return (
    <BaseIcon {...props} ref={ref} Icon={ArrowUpSVG}/>
  );
};

const ArrowUpIcon = forwardRef(ArrowUp);

export default ArrowUpIcon;
