/* generated by ./scripts/generate.ts, do not edit manually */

import React, {ForwardRefRenderFunction, forwardRef} from 'react';
import CheckFilledSVG from '../svg/CheckFilled.svg';
import BaseIcon, {BaseIconProps} from './BaseIcon';

interface IconProps extends Omit<BaseIconProps, 'Icon'> {}

const CheckFilled: ForwardRefRenderFunction<any, IconProps> = (
    props,
    ref,
) => {
  return (
    <BaseIcon {...props} ref={ref} Icon={CheckFilledSVG}/>
  );
};

const CheckFilledIcon = forwardRef(CheckFilled);

export default CheckFilledIcon;
