/* generated by ./scripts/generate.ts, do not edit manually */

import React, {ForwardRefRenderFunction, forwardRef} from 'react';
import InfoFilledSVG from '../svg/InfoFilled.svg';
import BaseIcon, {BaseIconProps} from './BaseIcon';

interface IconProps extends Omit<BaseIconProps, 'Icon'> {}

const InfoFilled: ForwardRefRenderFunction<any, IconProps> = (
    props,
    ref,
) => {
  return (
    <BaseIcon {...props} ref={ref} Icon={InfoFilledSVG}/>
  );
};

const InfoFilledIcon = forwardRef(InfoFilled);

export default InfoFilledIcon;
